#ifndef ARM_APP_H
#define ARM_APP_H

#include <stdint.h>
#include "arm_kinematics.h"

typedef struct {
    Arm_JointAngles_t current;
    Arm_JointAngles_t target;
    Arm_JointAngles_t last_ik;
    float home_wrist_x;
    float home_wrist_y;
    float wrist_x;
    float wrist_y;
    float wrist_r;
    uint8_t last_ik_ret;
    uint8_t last_limits_ok;
    uint8_t sw;
    uint8_t arm_stage;
    uint8_t arm_ready_key_pressed;
    uint8_t arm_ready_reached;
    uint8_t arm_ready_switch_snapshot;
    uint8_t arm_control_active;
    uint8_t kfs_mode;
    uint16_t kfs_height_mm;
    uint8_t delivery_origin_switch;
    uint8_t yaw_toggle_latched;
    uint8_t delivery_trigger_latched;
    uint32_t delivery_elapsed_ms;
    float j1_preset_deg;
    float j1_trim_deg;
    float j1_preset_target_deg;
    float suction_pitch_from_down_deg;
    uint8_t suction_pitch_world_mode;
    uint16_t ik_ok_count;
    uint16_t ik_fail_count;
    float he_cmd_pos;
    float he_follow_deg;
    uint16_t he_pitch_cmd_pos;
    uint16_t he_yaw_cmd_pos;
    uint8_t he_pitch_state;
    uint8_t he_yaw_state;
    uint16_t suction_move_time_ms;
    uint32_t he_direct_send_count;
    uint32_t he_direct_move_count;
    uint32_t he_direct_load_count;
    uint8_t he_direct_last_id;
    uint8_t he_direct_last_cmd;
    uint8_t he_direct_last_status;
    uint32_t he_direct_timeout_count;
    uint32_t he_direct_busy_count;
    uint8_t he_direct_fail_phase;
    uint32_t he_uart_gstate;
    uint32_t he_uart_rxstate;
    uint32_t he_uart_error_code;
    uint32_t he_uart_cr1;
    uint32_t he_uart_cr2;
    uint32_t he_uart_cr3;
    uint32_t he_uart_brr;
    uint32_t he_uart_isr_before;
    uint32_t he_uart_isr_after;
    uint32_t he_gpioa_moder;
    uint32_t he_gpioa_afrl;
    uint8_t air_pump_on;
    uint8_t air_valve_on;
    float j1_zero_abs_rad;
    float j1_cmd_abs_rad;
    float j1_cmd_speed_rad_s;
    float j1_remote_rate_deg_s;
    float j1_remote_speed_rad_s;
    float j1_error_deg;
    int16_t j1_remote_raw;
    uint8_t j1_zero_ready;
    uint8_t j1_limit_hit;
    uint32_t task_count;
    uint8_t dm_feedback_initialized;
    uint8_t dm_stop_flag;
    uint8_t dm_state;
    uint8_t dm_motor_id;
    float dm_position_rad;
    float dm_velocity_rad_s;
    float dm_torque_nm;
    float dm_pos_ref_rad;
    float dm_vel_ref_rad_s;
    uint32_t dm_decode_count;
    uint32_t dm_control_count;
    uint16_t dm_last_tx_id;
    uint16_t dm_last_rx_id;
    uint8_t dm_last_tx_ok;
} Arm_Debug_s;

extern volatile Arm_Debug_s arm_debug;

void Arm_Init(void);
void Arm_Task(void);

#endif
